# Generated by Django 5.0.6 on 2024-05-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="PublishPost",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
